nelmio_api_doc:
    areas:
        path_patterns:
            - ^/(?!(_|api/doc))
    documentation:
        info:
            title: SF Demo
            description: showcase project
            version: 1.0.0
