services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
            args:
                APP_ENV: dev
        container_name: company-register-api
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        environment:
            APP_ENV: dev
